paths:
  /api/products:
    get:
      summary: Get All Products
      tags:
        - Products
      responses:
        "200":
          description: All products
        "500":
          description: Server error
    post:
      summary: Created a product
      tags:
        - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
            example:
              name: TELEVISOR
              description: LCD 42 HZ
              stock: 12
              price: 533
              category: tecnologia
              code: 324fdasf2
              status: true
      responses:
        "200":
          description: Product created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              example:
                id: 123124fadsff
                name: TELEVISOR
                description: LCD 42 HZ
                stock: 12
                price: 533
                category: tecnologia
                code: 324fdasf2
                status: true
        "400":
          description: All fields required
        "500":
          description: Server error
  /api/product/{id}:
    get:
      summary: Get one product by id
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: Product identifier
      responses:
        "200":
          description: One product found
          content:
            application/json:
              schemas:
                $ref: "#components/schemas/Product"
              example:
                id: 123124fadsff
                name: TELEVISOR
                description: LCD 42 HZ
                stock: 12
                price: 533
                category: tecnologia
                code: 324fdasf2
                status: true
        "500":
          description: Server Error
    put:
      summary: Update product by id
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: Product identifier
      requestBody:
        content:
          application/json:
            schemas:
              $ref: "#components/requestBodies/updateProduct"
            example:
              name: TELEVISOR
              description: LCD 42 HZ
              stock: 12
              price: 533
              category: tecnologia
              code: 324fdasf2

      responses:
        "200":
          description: Product updated
          content:
            application/json:
              schemas:
                $ref: "#components/requestBodies/updateProduct"
              example:
                id: 123124fadsff
                name: TELEVISOR
                description: LCD 42 HZ
                stock: 12
                price: 533
                category: tecnologia
                code: 324fdasf2
                status: true
        "500":
          description: Server Error

    delete:
      summary: Delete product by id
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: Product identifier
      responses:
        "200":
          description: Product deleted
        "400":
          description: Product not found
        "500":
          description: Server error
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        stock:
          type: number
        price:
          type: number
        category:
          type: string
        code:
          type: string
        status:
          type: boolean
      example:
        name: TELEVISOR
        description: LCD 42 HZ
        stock: 12
        price: 533
        category: tecnologia
        code: 324fdasf2
        status: true
  requestBodies:
    updateProduct:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        stock:
          type: number
        price:
          type: number
        category:
          type: string
